# Hyprland Konfiguration

# Monitoreinstellungen und Positionen
exec_always --no-startup-id xrandr --output DP-1-1 --rotate right --auto
exec_always --no-startup-id xrandr --output DP-1-2 --rotate normal --auto
exec_always --no-startup-id xrandr --output eDP-1 --rotate normal --auto
exec_always --no-startup-id xrandr --output DP-1-1 --right-of DP-1-2
exec_always --no-startup-id xrandr --output DP-1-2 --right-of eDP-1

set $fm eDP-1
set $sm DP-1-1
set $tm DP-1-2

# Workspaces zuweisen
workspace 1 output $fm  
workspace 2 output $fm  
workspace 3 output $tm    
workspace 4 output $tm    
workspace 5 output $tm    
workspace 6 output $tm 
workspace 7 output $tm    
workspace 8 output $sm    
workspace 9 output $sm    
workspace 10 output $sm  

# Tastenkombinationen
bind=alt+h, move_left
bind=alt+j, move_down
bind=alt+k, move_up
bind=alt+l, move_right
bind=alt+shift+h, move_left 10
bind=alt+shift+j, move_down 10
bind=alt+shift+k, move_up 10
bind=alt+shift+l, move_right 10
bind=alt+b, split_horizontally
bind=alt+v, split_vertically
bind=mod+s, set_layout stacking
bind=mod+w, set_layout tabbed
bind=mod+e, toggle_split
bind=alt+q, close
bind=alt+z, exec evince
bind=alt+u, exec firefox
bind=alt+i, exec nautilus
bind=alt+o, exec nvim
bind=alt+p, exec gnome-calendar
bind=alt+=, exec nvim hyprland.conf
bind=alt+ü, exec endeavour
bind=alt+ö, exec nm-connection-editor
bind=alt+ä, exec pavucontrol
bind=alt+enter, exec kitty
bind=alt+shift+r, restart
bind=alt+shift+x, lock_screen
bind=alt+shift+e, exit_hyprland

# Fensterverhalten
focus_on_new  # Fokussiere neue Fenster
floating {     # Standard für schwebende Fenster
    border 2px
    color #ff0000
}

# Weitere Einstellungen hier

